apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: webapp
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: cicd  # Ensure this matches your service account's namespace
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
